[pytest]
addopts = -p no:cacheprovider
filterwarnings =
    ignore:Please use `import python_multipart` instead\.:PendingDeprecationWarning:starlette\.formparsers
    ignore:'crypt' is deprecated and slated for removal in Python 3\.13:DeprecationWarning:passlib\.utils
